website/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))

website/__init__.py
from flask import Flask, render_template, request, redirect
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = 'database.db'


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "ZD!c$8L4#1%q$as6vWo7"
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_NAME}"
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user, UserMixin


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("Incorrect password! Try again.", category='error')
        else:
            flash("Email does not exist.", category='error')

    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logged out!", category='error')
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')


        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists!", category='error')
        elif len(email) < 4:
            flash("Email must have at least 3 characters!", category='error')
        elif len(first_name) < 2:
            flash("First name must have at least one character!", category='error')
        elif password1 != password2:
            flash("Passwords do not match!", category='error')
        elif len(password1) < 7:
            flash("Password must contain at least 7 characters!", category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category='success')
            return redirect(url_for('views.home'))

    return render_template('sign_up.html', user=current_user)

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from BusinessLayer.scraper import *
from BusinessLayer.amazon import *
from BusinessLayer.tapaz import *
from .filter import *
import csv

views = Blueprint('views', __name__)
# amazon_data = []
# tapaz_data = []


@views.route('/', methods=["GET", "POST"])
def home():
    return render_template("home.html", user=current_user)


@views.route('/about')
def about():
	return render_template("about.html", title='About', user=current_user)


@views.route('/search', methods=['GET', 'POST'])
def search():
    item = request.form['search_item']
    amazon_data = []
    tapaz_data = []
    amazon_data.clear()
    tapaz_data.clear()
    amazon = AmazonScraper(item)
    amazon.get_data(item)
    tapaz = TapAzScraper(item)
    tapaz.get_data(item)


    if request.method == "POST":
        sites = request.form.getlist('site')
        min_price = float(request.form.get('from')) if request.form.get('from') != '' else 0.00
        max_price = float(request.form.get('to')) if request.form.get('to') != '' else 10000.00
        currency = request.form.get('currency')
        order = request.form.get('order')
        shipping = request.form.get('shipping')


    with open('BusinessLayer/results.csv', mode='r', encoding='utf-8') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        line_num = 0
        for row in csv_reader:
            if line_num != 0:
                if row['page'] == 'amazon':
                    if row['price'] != "":
                        shipping_option = "available"
                        row['price'] = convertCurrency(row['price'], currency, 'amazon')


                        if min_price < row['price'] < max_price:
                            amazon_ls = [row['title'], 'https://www.amazon.com/' + row['link'], row['price'], row['page'], shipping_option]
                        else:
                            continue
                    else:
                        shipping_option = "not available"
                        row['price'] = 0.00
                        amazon_ls = [row['title'], 'https://www.amazon.com/' + row['link'], row['price'], row['page'], shipping_option]

                
                    amazon_data = filterByShipping(amazon_ls, amazon_data, shipping)
                    filterByOrder(amazon_data, order)

                elif row['page'] == 'tapaz':
                    if row['price'] != "":
                        shipping_option = "available"
                        row['price'] = convertCurrency(row['price'], currency, 'tapaz')


                        if min_price < row['price'] < max_price:
                            tapaz_ls = [row['title'], 'https://tap.az' + row['link'], row['price'], row['page'], shipping_option]
                        else:
                            continue
                    else:
                        shipping_option = "not available"
                        row['price'] = 0
                        tapaz_ls = [row['title'], 'https://tap.az' + row['link'], row['price'], row['page'], shipping_option]


                    filterByShipping(tapaz_ls, tapaz_data, shipping)
                    filterByOrder(tapaz_data, order)

            line_num = line_num + 1

    return render_template('home.html', user=current_user, isSearching = True, amazonItems=amazon_data, tapazItems=tapaz_data, item=request.form.get('search_item'), sites=sites, min_price=min_price, max_price=max_price, currency=currency, order = request.form.get('order'))

website/templates/about.html
{% extends "base.html" %}
{% block content %}
	<br>
	<h1>About Page</h1>
{% endblock content %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% block head %} {% endblock %}
</head>
<div class="box">
  <form action="https://google.com/search">
    <input type="text" name="q">
    <input type="submit" value="Google Search">
  </form>
</div>vbar-dark" style="background-color: #2894a4;">
<div class="container">
  <a class="navbar-brand" href="/" style="font-size: 150%;"><b>WhereToBuy</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/about">About </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Websites
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://www.amazon.com/" target="_blank">Amazon</a>
          <a class="dropdown-item" href="https://tap.az/" target="_blank">tap.az</a>
        </div>
      </li>
    </ul>
  </div>
  <div class="collapse navbar-collapse" id="navbar" style="position: absolute; right: 10%;">
    <div class="navbar-nav">
      {% if user.is_authenticated %}
      <a class="btn btn-outline-success active" id="logout" href="/logout" role="button"
        style="border-color: #f3e458; background-color: #f5e870; color: #8f820a; margin: 5px;"><b>Logout</b></a>
      {% else %}
      <a class="btn btn-outline-success active" id="login" href="/login" role="button"
        style="border-color: #75bd8f; background-color: #87c59d; color: #3a7850; margin: 5px;"><b>Login</b></a>
      <a class="btn btn-outline-success active" id="sign-up" href="/sign-up" role="button"
        style="border-color: #53ac75; background-color: #64b483; color: #29563b; margin: 5px;"><b>Sign Up</b></a>
      {% endif %}
    </div>
  </div>
</div>
</nav>
</header>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
{% if category == "error" %}
<div class="alert alert-danger alert-dismissable fade show">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% else %}
<div class="alert alert-success alert-dismissable fade show">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
{% endfor %}
{% endif %}
{% endwith %}

<br>

<div class="container">
  {% block content %}
  <br>
  <form class="form-inline my-2 my-lg-0" action="{{ url_for('views.search') }}" method="POST">
    <section style="width: auto;">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search_item" style="width: auto;">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="search_button" value="Search"><i
          class="fa fa-search"></i></button>
    </section>

    <div class="row">
      <div class="column" style="width: auto; margin: 1cm;">
        <section>
          <h5 class="font-weight-bold" style="color: #089191;"><b>Websites</b></h5>
          <label class="form-check-label" for="amazon" style="font-size: medium;"><input class="form-check-input"
              type="checkbox" id="amazon" name="site" value="amazon">Amazon</label>
          <label class="form-check-label" for="tapaz" style="font-size: medium;"><input class="form-check-input"
              type="checkbox" id="tapaz" name="site" value="tapaz">TapAz</label>
        </section>
      </div>

      <div class="column" style="width: auto; margin: 1cm;">
        <h5 class="font-weight-bold mb-3" style="color: #089191;">Price</h5>
        <div class="d-flex mt-1">
          <div class="md-form md-outline my-0">
            <input id="from" type="text" name="from" class="form-control mb-0" placeholder="Min" style="width: 2.5cm;">
            <label for="from" style="font-size: medium;"></label>
          </div>
          <p class="px-2 mb-0 text-muted"> - </p>
          <div class="md-form md-outline my-0">
            <input id="to" type="text" name="to" class="form-control mb-0" placeholder="Max" style="width: 2.5cm;">
            <label for="to" style="font-size: medium;"></label>
          </div>
        </div>
      </div>

      <div class="column" style="width: auto; margin: 1cm;">
        <h5 class="font-weight-bold mb-3" style="color: #089191;">Currency</h5>
        <select name="currency" id="currency">
          <option value="default">Default</option>
          <option value="usd">USD</option>
          <option value="azn">AZN</option>
        </select>
      </div>

      <div class="column" style="width: auto; margin: 1cm;">
        <h5 class="font-weight-bold mb-3" style="color: #089191;">Sorting order</h5>
        <select name="order" id="order">
          <option value="default">Default</option>
          <option value="ascending">Ascending</option>
          <option value="descending">Descending</option>
        </select>
      </div>

      <div class="column" style="width: auto; margin: 1cm;">
        <section>
          <h5 class="font-weight-bold" style="color: #089191;"><b>Shipping</b></h5>
          <label class="form-check-label" for="shipping"><input class="form-check-input" type="checkbox" id="shipping"
              name="shipping" value="available">Available</label><br>
        </section>
      </div>
    </div>
  </form>
  <hr>
  <br>

  {% if isSearching %}
  <div class="row">
    {% if 'amazon' in sites %}
    <div class="column" value="amazon" style="width: 40%; margin: 1.5cm;">
      <h1 style="color: #ef8c2a;"><b>Amazon</b></h1>
      <br>
      {% for item in amazonItems %}
      <p><a href={{item[1]}} target="_blank">{{item[0]}}</a></p>
      {% if currency == 'azn' %}
      <p>{{item[2]}} ₼</p>
      {% else %}
      <p>${{item[2]}}</p>
      {% endif %}
      <hr>
      {% endfor %}
    </div>
    {% endif %}

    {% if 'tapaz' in sites %}
    <div class="column" value="tapaz" style="width: 40%; margin: 1.5cm;">
      <h1 style="color:#ed7014;"><b>TapAz</b></h1>
      <br>
      {% for item in tapazItems %}
      <p><a href={{item[1]}} target="_blank">{{item[0]}}</a></p>
      {% if currency == 'usd' %}
      <p>${{item[2]}}</p>
      {% else %}
      <p>{{item[2]}} ₼</p>
      {% endif %}
      <hr>
      {% endfor %}
    </div>
    {% endif %}
  </div>
  {% endif %}
  {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

website/templates/home.html
{% extends "base.html" %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<br>
<h1>This is Home Page</h1>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block head %}
<title>Login</title>
{% endblock %}
{% block content %}
<form method="POST">
    <br>
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">

    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">

    </div>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block head %}
<title>Sign-up</title>
{% endblock %}
{% block content %}
<form method="POST">
    <br>
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">

    </div>
    <div class="form-group">
        <label for="first_name">First Name</label>
        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter first name">

    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">

    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}